version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo installing sam
      - pip install --upgrade pip
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo installing npm packages
      - cd hello-world &&  npm install && cd ..
  build:
    commands:
      - echo build environment is `date`
      - echo build started at $ENV_NAME
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipelinetest-hanad --output-template-file sam-template.yaml
      #- aws cloudformation deploy --template-file sam-template.yaml --stack-name sam-stack-$ENV_NAME --capabilities CAPABILITY_IAM --parameter-overrides Environment=$ENV_NAME
  post_build:
    commands:
      - echo deployment completed at `date`
